### ISSUE TITLE
glog_catkin error

### ISSUE THREAD

**Issue by YouShaoze** [unr-arl/mbplanner_ws#6]
Dear developer：
I encountered the following problems when compiling ws:
Errors     << glog_catkin:make /home/ysz/mbplanner_ws/logs/glog_catkin/build.make.000.log
/bin/sh: 1: autoreconf: not found
make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-configure] Error 127
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2
It seems that it can't find the fix-unused-typedef-warning.patch of GLOG. But it's in the folder.

**Comment by MihirDharmadhikari** [comment]
Hi @YouShaoze,

Sorry for the late reply.
Can you specify which ubuntu and ROS distribution you are using?

Thanks,
Mihir

**Comment by MihirDharmadhikari** [comment]
Hi @YouShaoze,

After a little Googling I found the same issue faced by someone else on the glog_catkin repository [here](https://github.com/ethz-asl/aerial_mapper/issues/26). The issue was resolved by installing autoreconf:
```bash
sudo apt install dh-autoreconf
```
Can you try installing it and see if it works?

Thanks,
Mihir

**Comment by MihirDharmadhikari** [comment]
Closing the issue since the solution is posted and it is inactive for quite some time.
